version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up -d
  test:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run app yarn test:unit:coverage
      - run: docker-compose run api coverage run --source='.' manage.py test
      - run: docker-compose run api coverage report
  
workflows:
  version: 2

  commit:
    jobs:
      - build
      - test