version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://myuser@localhost:5432/circle_test
      - image: circleci/postgres:12
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
      - image: circleci/node:10.16.3
    steps:  
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python-pip python-dev libpq-dev postgresql postgresql-contrib
      - run:
        command: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run:
          command: |
            pip3 install virtualenv
            virtualenv env
            . env/bin/activate
            pip install djangorestframework psycopg2 django-cors-headers
      - run:
          name: Setup the database
          command: psql -h localhost -p 5432 -U myuser -d circle_test -a -f schema.sql
      - run:
          name: Running api tests
          command: |
            . env/bin/activate
            cd api/
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
      - run:
          name: Instal quasar
          command: |
            cd client/
            yarn global add @quasar/cli
      - run:
          name: Instal app dependencys
          command: |
            cd client/
            yarn install
      - run:
          name: Running app tests
          command: |
            cd client/
            quasar test --unit jest
